// RobotBuilder Version: 1.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.
#ifndef ROBOTMAP_H
#define ROBOTMAP_H
#include "WPILib.h"
/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
class RobotMap
{
public:
   // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
   static SpeedController* chassisleft_front;
   static Encoder* chassisleft_front_encoder;
   static SpeedController* chassisleft_back;
   static Encoder* chassisleft_back_encoder;
   static SpeedController* chassisright_front;
   static Encoder* chassisright_front_encoder;
   static SpeedController* chassisright_back;
   static Encoder* chassisright_back_encoder;
   static SpeedController* pickupArm;
   static SpeedController* pickupRollerArm;
   static Relay* pickupRollers;
   static Gyro* pickupArmAngleGyro;
   static SpeedController* launcherLauncherController;
   static AnalogChannel *sonar;
   static DigitalInput *lowerLimitSwitch;
   static DigitalInput *higherLimitSwitch;
   static DigitalInput *lowerLimitSwitch1;
   static DigitalInput *higherLimitSwitch1;
   // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
   static void init();
};
#endif
